apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "common.fullname" . }}-secret
data:
  {{- range $key, $value := .Values.secret }}
    {{ $key }}: {{ $value | b64enc | quote }}
    {{- end }}