apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: orders-destination
spec:
  host: local-orders
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 80